### ISSUE TITLE
Allow ECS credential provider ports to be configured to enable binding and integration testing

### ISSUE THREAD

**Issue by kggilmer** [awslabs/aws-c-auth#142]
As is the ports used to connect to the credential-providing service for ECS environments is [hard coded to 443/80](https://github.com/awslabs/aws-c-auth/blob/main/source/credentials_provider_ecs.c#L555).  These low ports present a problem for cases in which we wish to execute tests that exercise this credential provider as we cannot run a test service on these ports without changes to the host machine running the test.  

Expected behavior:
As a binding developer I can specify the ports used by the ECS credential provider to retrieve credentials

Actual behavior:
ECS credential provider will only read from 443/80

**Comment by bretambrose** [comment]
I think this was addressed with https://github.com/awslabs/aws-c-auth/pull/148
