### ISSUE TITLE
Potentially missing test files for sigV4

### ISSUE THREAD

**Issue by dnys1** [awslabs/aws-c-auth#160]
Hello, we are using the test suite for our SigV4 implementation. Most directories have exactly 10 files which describe the test, however the following have only 2:
- [tests/aws-signing-test-suite/v4/get-vanilla-query-order-key](https://github.com/awslabs/aws-c-auth/tree/main/tests/aws-signing-test-suite/v4/get-vanilla-query-order-key)
- [tests/aws-signing-test-suite/v4/get-vanilla-query-order-value](https://github.com/awslabs/aws-c-auth/tree/main/tests/aws-signing-test-suite/v4/get-vanilla-query-order-value)

Are these expected to share the missing files with another directory?

**Comment by bretambrose** [comment]
Those were probably in the original test suite we started with.  There were several tests that had flat-out wrong validation data in them and we skipped.  We should remove these.
