### ISSUE TITLE
default chain provider: add support for SSO generated credentials

### ISSUE THREAD

**Issue by grrtrr** [awslabs/aws-c-auth#164]
The AWS C++ [SDK](https://github.com/aws/aws-sdk-cpp) supports AWS SSO credentials [since version 1.9](https://github.com/aws/aws-sdk-cpp/issues/1433#issuecomment-1079267499).

As of June 2022, the `aws-c-auth` `aws_credentials_provider_default_chain` does not support SSO credentials,
which means it can not be used on systems that rely on SSO, or called from the AWS SDK  > 1.9.0 when using the 
CommonRunTime (CRT) extension for `PutObject/GetObject`.

(Related issue: support for STS credentials #157).

**Comment by yasminetalby** [comment]
Hello,

I am closing this issue as it was resolved by #189 .
If you have any further inquiries you can open a new issue within our repository.

Thank you very much for your time and collaboration.

Sincerely,

Yasmine
