### ISSUE TITLE
BUILD_TESTING=ON causes link error since version 0.6.26

### ISSUE THREAD

**Issue by thomas-roos** [awslabs/aws-c-auth#190]
Did work before with version 0.6.25
see [error.log](https://github.com/awslabs/aws-c-auth/files/11019455/error.log)

**Comment by graebm** [comment]
You also need to update aws-c-sdkutils to [v0.1.8](https://github.com/awslabs/aws-c-sdkutils/releases/tag/v0.1.8)

**Comment by thomas-roos** [comment]
TY
